### ISSUE TITLE
Stubbing and then restoring `getters` causes the wrapped method to be invoked

### ISSUE THREAD

**Issue by bradbarrow** [sinonjs/sinon#1124]
**_Details**_
- Sinon version : 1.17.5
- Other libraries you are using: mocha, chai
- Environment: Browser and Node v5.5.0
- Load method: Script tag and CDN hosted Sinon and / or webpack bundled sinon npm module 

**What did you expect to happen?**

When stubbing a getter on a class, and then restoring the stub, I expect that the stubbed getter (property) will never be invoked/accessed.

**What actually happens**

When I restore the stubbed getter, the original wrapped getter is invoked as a side effect.

**How to reproduce**

Stub a getter, then restore the stub and witness that the original getter is invoked:

https://codepen.io/foxwisp/pen/LkXXzd?editors=0010

**The cause**

https://github.com/sinonjs/sinon/blob/d24a1f1ac7ea500d3d185adb3821786d321f6a92/lib/sinon/util/core.js#L159

When restoring a wrapped method, there's a last ditch attempt to put the original method back that uses strict equality to compare the current value for `object[property]` against the stubbing value `method`. 

When `object[property]` is evaluated, it invokes the getter that was stubbed because it's already been restored using `Object.defineProperty` here:

https://github.com/sinonjs/sinon/blob/d24a1f1ac7ea500d3d185adb3821786d321f6a92/lib/sinon/util/core.js#L154

**Proposed Solutions**
- Don't do the strict check for `hasES5Support` cases...trust that the `Object.defineProperty` will work?
- For `hasES5Support` cases, don't compare the `object[property]` itself, but rather use `getPropertyDescriptor` and strictly compare those to avoid invoking the stubbed getter.

**Why is this an issue**

Often we stub to stub away some complexity that we don't want to have to setup / cost we don't want to incur. If the original method is going to be called by `stub.restore()` we're still going to incur the cost / require the setup to avoid exceptions.

I know there's an argument that getters should be simple and shouldn't even need to be stubbed, but if we can - they should work.

**Comment by fearphage** [comment]
@bradbarrow Thank you for the great level of detail. We appreciate it.

I believe this was already fixed on master. #1059

Someone just needs to port the fix.

**Comment by mroderick** [comment]
While investigating #1177, I created a runnable example for this issue: https://github.com/mroderick/sinon-issue-1177

This still fails in `master`.

**Comment by mroderick** [comment]
I have created a PR to add documentation for working with accessor methods, and have added a note saying this feature is current unstable.

https://github.com/sinonjs/sinon/pull/1182

**Comment by micheleDiSalvatoreLoveholidays** [comment]
Thanks @mroderick

**Comment by micheleDiSalvatoreLoveholidays** [comment]
@mroderick I followed your new documentation, but the problem doesn't look solved.

Here a new code case:
```javascript
      const instance = this.component.instance();
      const stub = sinon.stub(instance, 'selectedFlightMeals', { get: () => [{
        type: Immutable.fromJS({}),
      }] });
      const output = shallow(instance.render());
      expect(output.find('.class')).to.exist;
      stub.get.restore();
```

Here the output error
```log
TypeError: 'undefined' is not a function (evaluating 'stub.get.restore()')
```

**Comment by fatso83** [comment]
Should be fixed by #1194
