### ISSUE TITLE
Failure to Load Resources on sinonjs.org

### ISSUE THREAD

**Issue by qjd2413** [sinonjs/sinon#1662]
`/assets/` is incorrectly linked to (pointing to `/sinon//assets/` instead of simply `/assets/`). I have a feeling 
```
{{ "/assets/..." | prepend: site.baseurl }} -> {{ "/assets/..." }}
```
would fix it (which I'll test when I can).

**Comment by fatso83** [comment]
This is a bug in GitHub pages that started occurring on all GitHub pages today! It should be closed in a few hours when GitHub notices.

**Comment by mroderick** [comment]
Thank you for reporting it!

**Comment by fatso83** [comment]
I talked to support and they have fixed the issue a few hours ago. [My own site](http://holmevann.kopseng.no) was down for the same reason and they triggered a rebuild after fixing the issue. I have asked them to do the same for our site. 

It seems as if we might be subject to another bug as well, as we get redirected to another domain as well. Going to sinonjs.org/docs redirects to http://sinonjs-3231d9877a.drafts.github.io/sinon/releases/index.html

**Comment by fatso83** [comment]
Fixed after they rebuilt the site

**Comment by mroderick** [comment]
:+1:

**Comment by huanghuiquan** [comment]
http://sinonjs.org/  still broken，when it can been fix？thx

![image](https://user-images.githubusercontent.com/1880596/43303133-0f0ed9e6-91a1-11e8-8d73-2e578a6d3b44.png)

**Comment by mroderick** [comment]
@huanghuiquan that was probably a temporary network issue, it's working for everyone it seems

**Comment by huanghuiquan** [comment]
Sorry，It was my fail, I used `http` protocol while it should `https`
