### ISSUE TITLE
stub.onCall(#).yields(x).returns(y) returns undefined instead of y

### ISSUE THREAD

**Issue by nfriedly** [sinonjs/sinon#1736]
I just updated some code from sinon 1.x to 4.x to take advantage of the newer promise features, and tests that had been passing started failing. These tests were stubbing `http.request`, which both returns a value and calls a callback. The return `req` value changed to `undefined`, and so code that called `req.on(...)` started failing. 

* Sinon version : 4.4.5
* Environment   : Node.js 8.9.4, macOS
* Example: see below
* Other libraries you are using: just sinon + mocha in the example below

**What did you expect to happen?**
I expect the stub to return whatever I pass into `.returns()`

**What actually happens**
When `onCall()` is used, it returns `undefined`

**How to reproduce**

```js
var assert = require('assert')
var sinon = require('sinon');

describe('sinon yield + returns', function() {
    // this passes
    it('works without without onCall', () => {
        const stub = sinon.stub().yields('yield val').returns('return val');
        const cb = sinon.spy();
        const ret = stub(cb);
        assert.equal(ret, 'return val');
        assert.deepEqual(cb.args, [['yield val']]);
    });
    // this fails
    it('should return the correct value with onCall', () => {
        const stub = sinon.stub().onCall(0).yields('yield val').returns('return val');
        const cb = sinon.spy();
        const ret = stub(cb);
        assert.equal(ret, 'return val'); // throws because ret is undefined
        assert.deepEqual(cb.args, [['yield val']]);
    });
});
```

save the above example to a test.js file, install sinon, and run `npx mocha test.js`

**Comment by nfriedly** [comment]
Doh, I think https://github.com/sinonjs/sinon/pull/1724 might fix this.

**Comment by mroderick** [comment]
@nfriedly thank you for your contribution!

I've just published #1724 as `sinon@4.4.6` to npm. Can you confirm that it fixes the issue for you?

**Comment by nfriedly** [comment]
Hum, it actually doesn't seem to from a quick test:

```sh
MLREM1712156:test nathan.friedly$ npm ls sinon
nathan.friedly@1.0.0 /Users/nathan.friedly/test
└── sinon@4.4.6 

MLREM1712156:test nathan.friedly$ npx mocha test.js


  sinon yield + returns
    ✓ works without without onCall
    1) should return the correct value with onCall


  1 passing (8ms)
  1 failing

  1) sinon yield + returns
       should return the correct value with onCall:
     AssertionError [ERR_ASSERTION]: undefined == 'return val'
      at Context.it (test.js:18:16)
```

**Comment by nfriedly** [comment]
And yea, the "real" tests are still failing with `TypeError: Cannot read property 'on' of undefined`, so it looks like it's still an issue. I'll try and take a closer look at the sinon code.

**Comment by nfriedly** [comment]
I haven't figured out what's wrong, but here's a regression test: https://github.com/nfriedly/sinon/commit/3c86f699b2929b3cd1b9f2ef3d40fe1204e95306

Not sure if that makes sense in a PR on it's own, though.

**Comment by nfriedly** [comment]
I think I've figured out what's happening. The first behavior after an `.onCall(#)` gets applied to that call, but then it returns the original stub, not the `.onCall(#)` one, so the next behavior gets added as a defaultBehavior

**Comment by nfriedly** [comment]
Figured it out. It just took a little bending my brain around :)

**Comment by dixitsuneel** [comment]
@nfriedly 
Do we know when this will be fixed? Or at least can you tell us in which recent version it used to work so that I can switch over that version.

**Comment by nfriedly** [comment]
I have a pull request with the fix waiting to be merged in (#1738). So the next version to be released will hopefully include it. No idea on how long that will take, though.

I think I was on 1.17.7, so that version works, but I haven't taken the time to search through and find where it broke.

In the meanwhile, you can just do repeated `.onCall()`s like so:

```js
sinon.stub().onCall(0).yields('yield val').onCall(0).returns('return val');
```

That will work properly on the current release and continue working after my patch lands.
