### ISSUE TITLE
Failing chromium test on updating deps

### ISSUE THREAD

**Issue by fatso83** [sinonjs/sinon#2072]
* Sinon version : `master` (before updating) or branch `bug-updating-deps`
* Environment   : Chromium

**What did you expect to happen?**
All tests pass in all environments.

**What actually happens**
One test fails.

```
  1360 passing (919ms)
  4 pending
  1 failing

  1) fakeTimers.clock
       .useFakeTimers
         fakes provided methods:
     AssertionError: [refute.same] function onNextTick() {} expected not to be the same object as function onNextTick() {}
      at Object.fail (node_modules/@sinonjs/referee/lib/create-fail.js:5)
      at Object.fail (node_modules/@sinonjs/referee/lib/define-assertion.js:46)
      at assertion (node_modules/@sinonjs/referee/lib/define-assertion.js:68)
      at Function.referee.<computed>.<computed> [as same] (node_modules/@sinonjs/referee/lib/define-assertion.js:93)
      at Context.<anonymous> (test/util/fake-timers-test.js:1075)
```

**How to reproduce**

Check out `master` (c8ff2b8f). Run `npm update && npm test`.

**Comment by fatso83** [comment]
Tried to manually revert one package at a time (tried browserify, rollup, ++), without seeing a difference. 

Now trying the reverse using a script by just installing and testing one package at a time.

**Comment by fatso83** [comment]
Success. `browserify@16.3.0` does something different.

```bash
$ cat test-script.sh 
#!/bin/bash

set -e # exit on error
pkgs=(browserify@16.3.0 eslint@5.16.0 eslint-plugin-prettier@3.1.0 prettier@1.18.2 rollup-plugin-commonjs@9.3.4)
for pkg in $pkgs; do
    git reset --hard
    npm install $pkg
    npm test
done
```

**Comment by fatso83** [comment]
I can't find anything suspicious in the diff: https://github.com/browserify/browserify/compare/v16.2.3...v16.3.0?

**Comment by fatso83** [comment]
Wondering if this could be related (mentions sinon and lolex fake timers):
https://github.com/calvinmetcalf/process-nextick-args/commit/108596de940c73e78e0378a4084ab73ac846aed0

**Comment by mroderick** [comment]
It looks like a bug in `process-nextick-args` was fixed. Do you want to try again?

**Comment by fatso83** [comment]
Nothing has happened in that project for more than a year, so it should still fail. We could update all other packages, but this would remain a blocker for updating browserify.
